import { SessionProvider } from "next-auth/react";
import "./globals.css";
import localFont from "next/font/local"
import { auth } from "@/auth";
import { Toaster } from "@/components/ui/toaster"

const workSans = localFont({
  src: [
    {
      path: "./fonts/WorkSans-Black.ttf",
      weight: "900",
      style: "normal"
    },
    {
      path: "./fonts/WorkSans-ExtraBold.ttf",
      weight: "800",
      style: "normal"
    },
    {
      path: "./fonts/WorkSans-Bold.ttf",
      weight: "700",
      style: "normal"
    },
    {
      path: "./fonts/WorkSans-SemiBold.ttf",
      weight: "600",
      style: "normal"
    },
    {
      path: "./fonts/WorkSans-Medium.ttf",
      weight: "500",
      style: "normal"
    },
    {
      path: "./fonts/WorkSans-Regular.ttf",
      weight: "400",
      style: "normal"
    },
    {
      path: "./fonts/WorkSans-Thin.ttf",
      weight: "200",
      style: "normal"
    },
    {
      path: "./fonts/WorkSans-ExtraLight.ttf",
      weight: "100",
      style: "normal"
    },
  ],
  variable: "--font-work-sans"
})


export const metadata = {
  title: "Alumini Connection Platform",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  const session = await auth()
  
  return (
    <html lang="en">
      <SessionProvider session={session}>
        <body
          className={`${workSans.variable} bg-[#F4F2EE] `}

        >
          {children}
          <Toaster />
        </body>

      </SessionProvider>
    </html>
  );
}
